name: ia-util-venv
dependencies:
  - python=3.7
  - numpy=1.20.*
  - pip
  - pip:
    - h5py==3.6.0
    - PyQt5==5.15.4
    - pyqtgraph==0.12.1
    - scipy==1.6.3
    - vtk==9.0.3
    - xarray==0.20.2